### ISSUE TITLE
MergeBands stacking bands inconsistently

### ISSUE THREAD

**Issue by CathyJinJNCC** [jncc/eo-s1-workflow#6]
Dan has said that NE have noticed that the bands in the stacked files are some times the wrong way round. Waiting for an example to investigate further. Suspect the issue may be in the gdal command:

gdalbuildvrt -separate /vsistdout/ <vv tif> <vh tif> |gdal_translate -a_nodata nan -co BIGTIFF=YES -co TILED=YES -co COMPRESS=LZW --config CHECK_DISK_FREE_SPACE no /vsistdin/ <output file>

**Comment by felixMasonJncc** [comment]
This appears to have been resolved by the rework.
